car = input("Digite o nome do carro: ")
value_of_the_car = float(input("Digite o valor do carro: R$"))
consumption_per_liter = float(input("Digite o consumo por litro:"))

print("---------------------------------------------")
print(f"| Carro: {car}")
print(f"| Valor: {value_of_the_car}")
print(f"| Consumo por litro: {consumption_per_liter}")
print("---------------------------------------------")
