produto = input("Digite o nome do produto: ")
valor_do_produto = float(input("Digite o valor do produto: "))
desconto = float(input("Digite o desconto: % "))
valor_do_desconto = valor_do_produto * desconto / 100
valor_final =valor_do_produto - valor_do_desconto

produto2 = input("Digite o nome do produto: ")
valor_do_produto2 = float(input("Digite o valor do produto: "))
desconto_do_produto2 = float(input("Digite o desconto: % "))
valor_do_desconto_do_produto2 = valor_do_produto2 * desconto_do_produto2 / 100
valor_final_do_produto2 = valor_do_produto2 - valor_do_desconto_do_produto2

produto3 = input("Digite o nome do produto: ")
valor_do_produto3 = float(input("Digite o valor do produto: "))
desconto_do_produto3 = float(input("Digite o desconto: % "))
valor_do_desconto_do_produto3 = valor_do_produto3 * desconto_do_produto3 / 100
valor_final_do_produto3 = valor_do_produto3 - valor_do_desconto_do_produto3

produto4 = input("Digite o nome do produto: ")
valor_do_produto4 = float(input("Digite o valor do produto: "))
desconto_do_produto4 = float(input("Digite o desconto: % "))
valor_do_desconto_do_produto4 = valor_do_produto4 * desconto_do_produto4 / 100
valor_final_do_produto4 = valor_do_produto4 - valor_do_desconto_do_produto4

produto5 = input("Digite o nome do produto: ")
valor_do_produto5 = float(input("Digite o valor do produto: "))
desconto_do_produto5 = float(input("Digite o desconto: % "))
valor_do_desconto_do_produto5 = valor_do_produto5 * desconto_do_produto5 / 100
valor_final_do_produto5 = valor_do_produto5 - valor_do_desconto_do_produto5


print("-----------------------------------")
print(f"Produto: {produto}\nPreço final: {valor_final}")    
print("-----------------------------------")
print(f"Produto: {produto2}\nPreço final: {valor_final_do_produto2}")
print("-----------------------------------")
print(f"Produto: {produto3}\nPreço final: {valor_final_do_produto3}")
print("-----------------------------------")
print(f"Produto: {produto4}\nPreço final: {valor_final_do_produto4}")
print("-----------------------------------")
print(f"Produto: {produto4}\nPreço final: {valor_final_do_produto5}")
print("-----------------------------------")
